# This is the configuration used to check the rubocop source code.

#inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'cookbooks/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Vagrantfile'
    - 'config/initializers/devise.rb'
  TargetRubyVersion: 2.1

Documentation:
  Enabled: false

Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

#Style/IndentHeredoc:
#  EnforcedStyle: powerpack

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

# Offense count: 83
Metrics/AbcSize:
  Max: 19

# Offense count: 34
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 171

# Offense count: 25
Metrics/CyclomaticComplexity:
  Max: 7

# Offense count: 135
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 14

# Offense count: 12
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 156

Metrics/BlockLength:
  Max: 156

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
